spring:
  application:
    name: "card"
  profiles:
    active: "dev"
  datasource:
    url: jdbc:postgresql://localhost:5432/db_onebank
    username: user_onebank
    password: user_onebankpsw
  jpa:
    hibernate.ddl-auto: "update"
    show-sql: true

server:
  port: 8081
  url: "http://localhost:${server.port}"
  version: "1.0"
accounts:
  message: "Card server message 1234"

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      probes:
        enabled: true
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  info:
    env:
      enabled: true

info:
  app:
    name: "card"
    description: "Card microservice application"
    version: "1.0.0"
