spring:
  application:
    name: "notification"
  datasource:
    url: jdbc:postgresql://localhost:5432/db_onebank
    username: user_onebank
    password: user_onebankpsw
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
  profiles:
    active: "dev"
accounts:
  message: "Card server message 1234"

server:
  port: 8082
  url: "http://localhost:${server.port}"

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/