spring:
  application:
    name: "transaction"
  datasource:
    url: jdbc:postgresql://localhost:5432/db_onebank
    username: user_onebank
    password: user_onebankpsw
  jpa:
    hibernate.ddl-auto: "update"
    show-sql: true
  config:
    import: "optional:configserver:http://localhost:8071/"
  profiles:
    active: "dev"
server:
  port: 8084
  url: "http://localhost:${server.port}"
accounts:
  message: "Transaction server message 1234"

# Spring actuator enable all api's
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    shutdown:
      access: unrestricted
    health:
      probes:
        enabled: true
  info:
    env:
      enabled: true

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

info:
  app:
    name: "transaction"
    description: "Codeuz microservice Transaction application"
    version: "1.0.0"

logging:
  level:
    dasturlash:
      uz:
        transaction: INFO
